query jobsByCompany($companyId: ID!) {
  countries {
    jobs(where: { company: { id: $companyId } }) {
      id
      title
      commitment {
        id
        title
      }
      company {
        id
        name
      }
      cities {
        id
        name
        country {
          id
          name
        }
      }
      company {
        id
        name
      }
      postedAt
    }
  }
}
