query FilterJobs(
  $title: String
  $companyId: ID
  $countryId: ID
  $order: JobOrderByInput
) {
  countries {
    jobs(
      orderBy: $order
      where: {
        title_contains: $title
        AND: {
          company: { id_contains: $companyId }
          AND: { countries_every: { id_contains: $countryId } }
        }
      }
    ) {
      id
      title
      commitment {
        id
        title
      }
      company {
        id
        name
      }
      cities {
        id
        name
        country {
          id
          name
        }
      }
      company {
        id
        name
      }
      postedAt
    }
  }
}
